export const mockImmobili = [
    {
        id: 1,
        slug: "immobile-1",
        titolo_descrittivo: "Appartamento in centro",
        indirizzo_completo: "Via Roma, 1, Milano",
        descrizione: "Bellissimo appartamento in centro a Milano.",
        mq: 100,
        bagni: 2,
        locali: 3,
        posti_letto: 4,
        immagini: [{ nome_immagine: "image1.jpg" }],
        tipi_alloggio: [{ id: 1, nome_tipo_alloggio: "Appartamento" }],
        voto_medio: 4.5,
        heartCount: 10,
        recensioni: [
            {
                username: "utente1",
                voto: 5,
                recensione: "Ottimo appartamento!",
                data: "2023-10-01",
            },
        ],
    },
    {
        id: 2,
        slug: "immobile-2",
        titolo_descrittivo: "Villa con piscina",
        indirizzo_completo: "Via Verdi, 10, Roma",
        descrizione: "Splendida villa con piscina e giardino.",
        mq: 300,
        bagni: 4,
        locali: 6,
        posti_letto: 8,
        immagini: [{ nome_immagine: "image2.jpg" }],
        tipi_alloggio: [{ id: 2, nome_tipo_alloggio: "Villa" }],
        voto_medio: 4.8,
        heartCount: 15,
        recensioni: [
            {
                username: "utente2",
                voto: 5,
                recensione: "Villa fantastica!",
                data: "2023-09-15",
            },
        ],
    },
    {
        id: 3,
        slug: "immobile-3",
        titolo_descrittivo: "Monolocale moderno",
        indirizzo_completo: "Via Dante, 5, Firenze",
        descrizione: "Monolocale moderno e accogliente.",
        mq: 50,
        bagni: 1,
        locali: 1,
        posti_letto: 2,
        immagini: [{ nome_immagine: "image3.jpg" }],
        tipi_alloggio: [{ id: 1, nome_tipo_alloggio: "Appartamento" }],
        voto_medio: 4.2,
        heartCount: 8,
        recensioni: [
            {
                username: "utente3",
                voto: 4,
                recensione: "Molto carino e funzionale.",
                data: "2023-08-20",
            },
        ],
    },
    {
        id: 4,
        slug: "immobile-4",
        titolo_descrittivo: "Casa di campagna",
        indirizzo_completo: "Via delle Rose, 12, Siena",
        descrizione: "Casa di campagna immersa nel verde.",
        mq: 200,
        bagni: 3,
        locali: 5,
        posti_letto: 6,
        immagini: [{ nome_immagine: "image4.jpg" }],
        tipi_alloggio: [{ id: 3, nome_tipo_alloggio: "Casa" }],
        voto_medio: 4.7,
        heartCount: 12,
        recensioni: [
            {
                username: "utente4",
                voto: 5,
                recensione: "Perfetta per una vacanza rilassante.",
                data: "2023-07-10",
            },
        ],
    },
    {
        id: 5,
        slug: "immobile-5",
        titolo_descrittivo: "Attico panoramico",
        indirizzo_completo: "Via del Mare, 8, Napoli",
        descrizione: "Attico con vista panoramica sul mare.",
        mq: 150,
        bagni: 2,
        locali: 4,
        posti_letto: 5,
        immagini: [{ nome_immagine: "image5.jpg" }],
        tipi_alloggio: [{ id: 1, nome_tipo_alloggio: "Appartamento" }],
        voto_medio: 4.9,
        heartCount: 20,
        recensioni: [
            {
                username: "utente5",
                voto: 5,
                recensione: "Vista mozzafiato!",
                data: "2023-06-05",
            },
        ],
    },
    {
        id: 6,
        slug: "immobile-6",
        titolo_descrittivo: "Rustico ristrutturato",
        indirizzo_completo: "Via dei Colli, 3, Verona",
        descrizione: "Rustico ristrutturato con materiali di pregio.",
        mq: 180,
        bagni: 3,
        locali: 5,
        posti_letto: 6,
        immagini: [{ nome_immagine: "image6.jpg" }],
        tipi_alloggio: [{ id: 3, nome_tipo_alloggio: "Casa" }],
        voto_medio: 4.6,
        heartCount: 11,
        recensioni: [
            {
                username: "utente6",
                voto: 5,
                recensione: "Molto accogliente e ben arredato.",
                data: "2023-05-15",
            },
        ],
    },
    {
        id: 7,
        slug: "immobile-7",
        titolo_descrittivo: "Loft industriale",
        indirizzo_completo: "Via Milano, 20, Torino",
        descrizione: "Loft in stile industriale con ampi spazi.",
        mq: 120,
        bagni: 2,
        locali: 2,
        posti_letto: 3,
        immagini: [{ nome_immagine: "image7.jpg" }],
        tipi_alloggio: [{ id: 1, nome_tipo_alloggio: "Appartamento" }],
        voto_medio: 4.3,
        heartCount: 9,
        recensioni: [
            {
                username: "utente7",
                voto: 4,
                recensione: "Spazioso e moderno.",
                data: "2023-04-10",
            },
        ],
    },
    {
        id: 8,
        slug: "immobile-8",
        titolo_descrittivo: "Baita in montagna",
        indirizzo_completo: "Via delle Alpi, 7, Trento",
        descrizione: "Baita in montagna con vista sulle Alpi.",
        mq: 140,
        bagni: 2,
        locali: 4,
        posti_letto: 5,
        immagini: [{ nome_immagine: "image8.jpg" }],
        tipi_alloggio: [{ id: 3, nome_tipo_alloggio: "Casa" }],
        voto_medio: 4.8,
        heartCount: 14,
        recensioni: [
            {
                username: "utente8",
                voto: 5,
                recensione: "Perfetta per una vacanza invernale.",
                data: "2023-03-20",
            },
        ],
    },
    {
        id: 9,
        slug: "immobile-9",
        titolo_descrittivo: "Casa al mare",
        indirizzo_completo: "Via del Sole, 15, Bari",
        descrizione: "Casa al mare con accesso diretto alla spiaggia.",
        mq: 130,
        bagni: 2,
        locali: 4,
        posti_letto: 6,
        immagini: [{ nome_immagine: "image9.jpg" }],
        tipi_alloggio: [{ id: 3, nome_tipo_alloggio: "Casa" }],
        voto_medio: 4.7,
        heartCount: 13,
        recensioni: [
            {
                username: "utente9",
                voto: 5,
                recensione: "Ideale per una vacanza estiva.",
                data: "2023-02-15",
            },
        ],
    },
    {
        id: 10,
        slug: "immobile-10",
        titolo_descrittivo: "Appartamento con terrazza",
        indirizzo_completo: "Via Garibaldi, 9, Genova",
        descrizione: "Appartamento con ampia terrazza panoramica.",
        mq: 110,
        bagni: 2,
        locali: 3,
        posti_letto: 4,
        immagini: [{ nome_immagine: "image10.jpg" }],
        tipi_alloggio: [{ id: 1, nome_tipo_alloggio: "Appartamento" }],
        voto_medio: 4.5,
        heartCount: 10,
        recensioni: [
            {
                username: "utente10",
                voto: 5,
                recensione: "Terrazza fantastica!",
                data: "2023-01-10",
            },
        ],
    },
    {
        id: 11,
        slug: "immobile-11",
        titolo_descrittivo: "Villa moderna",
        indirizzo_completo: "Via della Libertà, 5, Palermo",
        descrizione: "Villa moderna con piscina e giardino.",
        mq: 250,
        bagni: 3,
        locali: 5,
        posti_letto: 7,
        immagini: [{ nome_immagine: "image11.jpg" }],
        tipi_alloggio: [{ id: 2, nome_tipo_alloggio: "Villa" }],
        voto_medio: 4.9,
        heartCount: 18,
        recensioni: [
            {
                username: "utente11",
                voto: 5,
                recensione: "Villa stupenda!",
                data: "2022-12-05",
            },
        ],
    },
    {
        id: 12,
        slug: "immobile-12",
        titolo_descrittivo: "Casale in campagna",
        indirizzo_completo: "Via dei Fiori, 2, Perugia",
        descrizione: "Casale in campagna con ampio terreno.",
        mq: 220,
        bagni: 3,
        locali: 5,
        posti_letto: 6,
        immagini: [{ nome_immagine: "image12.jpg" }],
        tipi_alloggio: [{ id: 3, nome_tipo_alloggio: "Casa" }],
        voto_medio: 4.6,
        heartCount: 12,
        recensioni: [
            {
                username: "utente12",
                voto: 5,
                recensione: "Perfetto per una vacanza rilassante.",
                data: "2022-11-15",
            },
        ],
    },
    {
        id: 13,
        slug: "immobile-13",
        titolo_descrittivo: "Appartamento di lusso",
        indirizzo_completo: "Via Montenapoleone, 3, Milano",
        descrizione: "Appartamento di lusso nel cuore di Milano.",
        mq: 180,
        bagni: 3,
        locali: 4,
        posti_letto: 5,
        immagini: [{ nome_immagine: "image13.jpg" }],
        tipi_alloggio: [{ id: 1, nome_tipo_alloggio: "Appartamento" }],
        voto_medio: 4.8,
        heartCount: 16,
        recensioni: [
            {
                username: "utente13",
                voto: 5,
                recensione: "Lusso e comfort.",
                data: "2022-10-10",
            },
        ],
    },
    {
        id: 14,
        slug: "immobile-14",
        titolo_descrittivo: "Chalet in montagna",
        indirizzo_completo: "Via delle Nevi, 6, Bolzano",
        descrizione: "Chalet in montagna con vista sulle Dolomiti.",
        mq: 160,
        bagni: 2,
        locali: 4,
        posti_letto: 5,
        immagini: [{ nome_immagine: "image14.jpg" }],
        tipi_alloggio: [{ id: 3, nome_tipo_alloggio: "Casa" }],
        voto_medio: 4.7,
        heartCount: 14,
        recensioni: [
            {
                username: "utente14",
                voto: 5,
                recensione: "Perfetto per una vacanza invernale.",
                data: "2022-09-20",
            },
        ],
    },
    {
        id: 15,
        slug: "immobile-15",
        titolo_descrittivo: "Appartamento con giardino",
        indirizzo_completo: "Via dei Pini, 4, Bologna",
        descrizione: "Appartamento con giardino privato.",
        mq: 130,
        bagni: 2,
        locali: 3,
        posti_letto: 4,
        immagini: [{ nome_immagine: "image15.jpg" }],
        tipi_alloggio: [{ id: 1, nome_tipo_alloggio: "Appartamento" }],
        voto_medio: 4.5,
        heartCount: 11,
        recensioni: [
            {
                username: "utente15",
                voto: 5,
                recensione: "Giardino bellissimo!",
                data: "2022-08-15",
            },
        ],
    },
];

export const mockTipiAlloggio = [
    { id: 1, nome_tipo_alloggio: "Appartamento" },
    { id: 2, nome_tipo_alloggio: "Villa" },
    { id: 3, nome_tipo_alloggio: "Casa" },
    // ...altri tipi di alloggio...
];
